language: php

php:
    - 7.2

env:
  global:
    - PHALCON_VERSION="v3.4.5"
    - DB_NAME="servicelayer_test"

git:
  depth: 1

matrix:
  fast_finish: true

cache:
  timeout: 604800
  directories:
    - $HOME/.composer/cache

services:
  - mysql
  - memcached

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo mysql -e "USE mysql; UPDATE user SET authentication_string=PASSWORD('%%travis%%') WHERE user='root'; UPDATE user set plugin='mysql_native_password'; FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -p%%travis%%
  - sudo service mysql restart

install:
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - '(cd cphalcon/build; bash install &>/dev/null && phpenv config-add ../tests/_ci/phalcon.ini &> /dev/null && cd ../..;)'
  - travis_retry composer update --no-interaction --no-progress --no-ansi --no-suggest

before_script:
  - mysql -u root -p%%travis%% -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME} charset=utf8mb4 collate=utf8mb4_unicode_ci;"
  - mysql -u root -p%%travis%% ${DB_NAME} < tests/_data/dump.sql
  - cp .env.dist .env

script:
  - vendor/bin/codecept clean
  - vendor/bin/codecept build --quiet
  - vendor/bin/codecept run --coverage --coverage-xml

jobs:
  include:
    - stage: Test coverage
      if: branch = master AND type = push
      php: 7.2
      script:
        - make coverage
      after_script:
        - composer global require php-coveralls/php-coveralls ^2.2
        - ~/.composer/vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml

notifications:
  email:
    - dominic@headcrumbs.io
