language: php

php:
    - 7.4

os: linux

dist: bionic

env:
  global:
    - PHALCON_VERSION="v4.1.0"
    - DB_NAME="servicelayer_test"

git:
  depth: 1

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - gdb
      - libsodium-dev

cache:
  timeout: 604800
  directories:
    - $HOME/.composer/cache

services:
  - mysql
  - memcached
  - redis

before_install:
  # db
  - sudo mysql -e "USE mysql; UPDATE user SET authentication_string=PASSWORD('%%travis%%') WHERE user='root'; UPDATE user set plugin='mysql_native_password'; FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -p%%travis%%
  - sudo service mysql restart
  # php ini settings
  - php -i
  - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo memory_limit = -1 >> $INI
  - echo opcache.enable_cli = 1 >> $INI
  # suppress git advisories
  - git config --global advice.detachedHead false

install:
  - .ci/install-extensions.sh
  - .ci/install-phalcon.sh
  - travis_retry composer update --no-interaction --no-progress --no-ansi --no-suggest --ignore-platform-reqs

before_script:
  - phpenv config-rm xdebug.ini
  - pecl install pcov
  - mysql -u root -p%%travis%% -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME} charset=utf8mb4 collate=utf8mb4_unicode_ci;"
  - mysql -u root -p%%travis%% ${DB_NAME} < tests/_data/dump.sql
  - cp .env.dist .env

script:
  - vendor/bin/codecept clean
  - vendor/bin/codecept build --quiet
  - vendor/bin/codecept run --coverage --coverage-xml

jobs:
  include:
    - stage: Test coverage
      if: branch = 4.x AND type = push
      php: 7.4
      script:
        - make coverage
      after_script:
        - composer global require php-coveralls/php-coveralls ^2.4
        - ~/.composer/vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml

notifications:
  email:
    - dominic@headcrumbs.io
